version: "3.7"

services:
  web:
    container_name: web-container
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
