version: "3.7"

services:
  web:
    container_name: web-container
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
